### ISSUE TITLE
Add empty preslot

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Opex#2]
From @ArwynFr 
Add a preslot with no weapon and only fatigues in the grey lockers

**Comment by ImplicitDeny** [comment]
Same as #1 : assignated to @AkenoSyh for training purposes. Can be tried on the script version while this repo is in hard dev state

**Comment by ImplicitDeny** [comment]
@AkenoSyh the repo is now stable enough for you to proceed with fixing this issue 😃

**Comment by ArwynFr** [comment]
Note : the preslot will go to the red lockers now :)
