### ISSUE TITLE
Adjust author properties to better reflect the collective piece of work

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Opex#26]
Current author string only mentions "[-GSRI-] Cheitan". It would be more relevant to change it, either to a detailed list of contributors, or to a very simple "GSRI Team".

**Comment by ArwynFr** [comment]
I have very limited contributions and you own 90% of commits.
I think it is sensible to use your name as author for the mod.

I you prefer to attribute the mod collectively, please use `www.gsri.team`

**Comment by ImplicitDeny** [comment]
I was also thinking about @Seenri : most of his work is embedded directly in the SCMS mod, but some of these items have been requested specifically for the Normandie. I'll probably attribute collectively with the team's URL
