### ISSUE TITLE
Add support for ACE arsenal on red lockers

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/GSRI-Opex#5]
Also regroup with BI arsenal action in a common "arsenal" parent ACE ineteraction (similar to #4)

**Comment by ImplicitDeny** [comment]
It seems that ACE arsenal cannot be under a parent action (see https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_initBox.sqf)

**Comment by ImplicitDeny** [comment]
Alternative idea : create the ACE arsenal the default way, then try to "move" the action by manually modifying the action path. Currently trying to achieve this

**Comment by ImplicitDeny** [comment]
Nevermind, found a wayyyy cleaner workaround : https://github.com/acemod/ACE3/blob/master/addons/arsenal/functions/fnc_openBox.sqf

**Comment by ArwynFr** [comment]
Do you have a fix commit sha to provide before closing ?

**Comment by ImplicitDeny** [comment]
It is closed, automatically from commit https://github.com/team-gsri/GSRI-Opex/commit/c44da7c80af3f62bb2b15e29e1a3445158b90c85, see above

**Comment by ArwynFr** [comment]
Perhaps I should sleep instead of reviewing projects at night ^^
