### ISSUE TITLE
Add ACE medical "doctor" status switching from lockers

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/GSRI-Opex#6]
title

**Comment by ImplicitDeny** [comment]
Shouldn't we place the medical skills selection on a different place than gear selection ?
Alternatively, should we manage the skill based on the steam ID ?

**Comment by ArwynFr** [comment]
As already discussed, another place to change medic status is a waste of time for players, as they will go to briefing and then know what is the mission and roles. They will go to the locker to get equipment, and change medic status if needed. Then they will rendez-vous to the meeting point.

As for steam id, it is not yet decided to go this way.

**Comment by ImplicitDeny** [comment]
Done https://github.com/team-gsri/GSRI-Opex/commit/0f8dc3bbe8284d290d652049d9b9ffbddbf8e60b
