### ISSUE TITLE
String entry for naval group is broken

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Opex#67]
When in map, the naval group entry appears blank, but the task type is correctly displayed. Ship's strings are also correctly displayed. Might be a problem with string formatting at some point.

**Comment by ImplicitDeny** [comment]
Will be fixed in #76

**Comment by ArwynFr** [comment]
#76 was merge, is this issue solved ?

**Comment by ImplicitDeny** [comment]
Yep, solved, but the string displayed is the one as localized on the server. This is due to how the task framework is designed, and cannot be altered without a shit-ton of useless, fragile code. So we might let it "as is".

Currently discussing with modding veterans and BI devs to see if this can be changed, as localizing on clients would be more convenient AND more efficient.
