### ISSUE TITLE
Consider moving preslots functions into GSRI Gear

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Opex#74]
Preslots are not exactly "Opex-type" mechanics, and might be more suited in the GSRI Gear mod.
We could rewrite and refactor these functions, allowing for more flexibility if needed.

**Comment by ImplicitDeny** [comment]
Should we stop using an ACE action on a locker and instead move to a publicly available default loadout inside ACE arsenal itself ? https://ace3.acemod.org/wiki/framework/arsenal-framework.html#4-default-loadouts

**Comment by ArwynFr** [comment]
I'm not in favor due to the fact that not everyone uses ACE arsenal.
Also it requires 3 more steps to load a default loadout than an ACE interaction.
I think that worens UX.
