### ISSUE TITLE
Add OPEX to 3den mods

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/GSRI-Opex#78]
Addon should use `is3DENmod = 1` since it adds custom properties to the frigate. This option adds a warning of possible loss of custom attributes and prompts to install missing editor mod(s) when an unmodded editor opens a mission edited with the mod.
Source : https://community.bistudio.com/wiki/Eden_Editor:_Modding#Addon_Configuration

**Comment by ImplicitDeny** [comment]
To be discussed... Custom attributes are precisely not a dependency, that's a willingful choice
