### ISSUE TITLE
Add CBA versionning system ?

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/GSRI-Opex#9]
https://github.com/CBATeam/CBA_A3/wiki/Versioning-System

@ArwynFr Is it of any use with our addon's signature check ?

**Comment by ArwynFr** [comment]
I'd say no, since OPEX is not expected to be a public mod. Our core mods are signed again on every release so people need our version of the pack. They can't connect with a different version.

However, it would be useful to GZM since that mod is for public destination.
